project:
  type: book
  output-dir: docs

book:
  title: "Matematicas aplicadas"
  author: "Susana Hernández"
  date: "22/8/2023"
  cover-image: 'cover.png'
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - Tarea1.qmd
    - Tarea2.qmd
    - Tarea3.qmd
    - Tarea4.qmd
    - Tarea5.qmd
    - Tarea6.qmd
    - Tarea7.qmd
    - Tarea8.qmd
    - Tarea9.qmd
    - Tarea10.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



