# Tarea 7

::: {#exr-1}

Sea $W(t)$ un Movimiento Browniano y $Z_{i}$ una colección de variables aleatorias i.i.d, con distribución $N\left(0,\frac{\delta t}{4}\right)$.\
Pruebe que la suma
$$
\sum_{i=0}^{L}Z_{i}\left(W(t_{i+1})-W(t_{i})\right),
$$
tiene valor esperado igual a cero y una varianza de $O(\delta t)$.

:::
:::{.proof}
Sin perdida de generalidad dado como estan definidas $Z_{i}$ y $W(t_{i+1})-W(t_{i})$ podemos suponer que son variables aleatorias independientes para cada $i=1,\dots ,L$. Entonces

\begin{eqnarray*}
\mathbb{E}\left[\sum_{i=0}^{L}Z_{i}\left(W(t_{i+1})-W(t_{i})\right)\right] & = &  \sum_{i=0}^{L}\mathbb{E}\left[Z_{i}\left(W(t_{i+1})-W(t_{i})\right)\right]\\
& = &  \sum_{i=0}^{L}\mathbb{E}(Z_{i})\mathbb{E}\left(W(t_{i+1})-W(t_{i})\right)\\
& = & 0 \quad\text{ ya que, por hipótesis, }\mathbb{E}(Z_{i})=0\text{ y }\mathbb{E}\left(W(t_{i+1})-W(t_{i})\right)=0
\end{eqnarray*}
$$
\therefore \mathbb{E}\left[\sum_{i=0}^{L}Z_{i}\left(W(t_{i+1})-W(t_{i})\right)\right]=0.
$$
Ahora calculemos la varianza; sabemos que $Var(X)=\mathbb{E}(X^{2})-(\mathbb{E}(X))^{2}$, sustituyendo resulta

\begin{eqnarray*}
Var\left[\sum_{i=0}^{L}Z_{i}\left(W(t_{i+1})-W(t_{i})\right)\right] & = &   \mathbb{E}\left[\left(\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\right)^{2}\right]-\left(\mathbb{E}\left[\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\right]\right)^{2}\\
& = &  \mathbb{E}\left[\left(\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\right)^{2}\right]\quad\text{ usando el hecho que tiene valor esperado igual a 0}.
\end{eqnarray*}
Por el Teorema multinomial, se tiene que

\begin{eqnarray*}
\mathbb{E}\left[\left(\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\right)^{2}\right] & = &  \mathbb{E}\left[\sum_{i=0}^{L} \left[Z_{i}(W(t_{i+1})-W(t_{i}))\right]^{2}+2\sum_{i\neq j}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))Z_{j}(W(t_{j+1})-W(t_{j}))\right]\\
& = &  \sum_{i=0}^{L} \mathbb{E}\left[Z_{i}(W(t_{i+1})-W(t_{i}))\right]^{2}+2\sum_{i\neq j}^{L} \mathbb{E}\left[Z_{i}(W(t_{i+1})-W(t_{i}))Z_{j}(W(t_{j+1})-W(t_{j}))\right].
\end{eqnarray*}
Dado que $i\neq j$, sin perdida de generalidad podemos suponer que $i<j$, entonces

\begin{eqnarray*}
\mathbb{E}\left[Z_{i}(W(t_{i+1})-W(t_{i}))Z_{j}(W(t_{j+1})-W(t_{j}))\right] & = &  \mathbb{E}\{ \mathbb{E}\left[Z_{i}(W(t_{i+1})-W(t_{i}))Z_{j}(W(t_{j+1})-W(t_{j}))|\mathcal{F}_{j}\right]
\}\\
& = & \mathbb{E}\{[Z_{i}(W(t_{i+1})-W(t_{i}))Z_{j} ]\mathbb{E}\left[(W(t_{j+1})-W(t_{j}))|\mathcal{F}_{j}\right]\}\\
& = & 0
\end{eqnarray*}
Por otro lado,

\begin{eqnarray*}
\mathbb{E}\left[Z_{i}(W(t_{i+1})-W(t_{i}))\right]^{2} & = &  \mathbb{E}\{ \mathbb{E}\left[Z_{i}^{2}(W(t_{i+1})-W(t_{i}))^{2}|\mathcal{F}_{i}\right]
\}\\
& = & \mathbb{E}\{Z_{i}^{2}\mathbb{E}\left[(W(t_{i+1})-W(t_{i}))^{2}|\mathcal{F}_{i}\right]\}\\
& = & \mathbb{E}[Z_{i}^{2}](t_{i+1}-t_{i})\\
& = & \dfrac{\delta t}{4}(t_{i+1}-t_{i}),
\end{eqnarray*}
sustituyendo todo lo anterior, resulta
\begin{eqnarray*}
Var\left[\sum_{i=0}^{L}Z_{i}\left(W(t_{i+1})-W(t_{i})\right)\right] & = &  \sum_{i=0}^{L}\dfrac{\delta t}{4}(t_{i+1}-t_{i})\\
& = &  \dfrac{\delta t}{4}(t_{L+1}-t_{0}).
\end{eqnarray*}
Para un $L$ suficientemente grande podemos considerar que, dado un $\varepsilon>0$, tal que, $(t_{L+1}-t_{0})\leq\dfrac{\varepsilon}{4}$, así
$$
 Var\left[\sum_{i=0}^{L}Z_{i}\left(W(t_{i+1})-W(t_{i})\right)\right]\leq \varepsilon\delta t.
$$
Por lo tanto, con esto se concluye que, la varianza es de orden $\delta t$.
:::

::: {#exr-2}
La regla del punto medio de la integral de Riemann de una función $h\in C^{2}([a,b])$ sobre una partición de $L$ puntos del intervalo $[a,b]$ está dada por,
$$
\int_{a}^{b}h(t)dt=\lim_{\delta t\to 0,\,L\to\infty}\sum_{i=0}^{L}h\left(\dfrac{t_{i}+t_{i+1}}{2}\right)\delta t.
$$
Use la relación
$$
W\left(\frac{t_{i}+t_{i+1}}{2}\right)=\frac{1}{2}(W(t_{i})+W(t_{i+1}))+ \underbrace{Z_{i}}_{i.i.d.\sim N(0,\delta t/4)},
$$
y el ejercicio anterior para demostrar que la regla del punto medio de la integral de Riemann implica que
$$
\int_{0}^{T}W(t)dW(t)=\frac{1}{2}W(T)^{2}.
$$
:::

:::{.proof}
Sea $\Delta_{L}=\{0=t_{0},t_{1},\dots,t_{L-1},t_{L}=T\}$ una partición del intervalo $[0,T]$.
De la regla del punto medio, aplicada para $h(t)=W(t)$, se tiene que

\begin{eqnarray*}
\int_{0}^{T}W(t)dW(t) & = & \lim_{\delta t\to 0,\,L\to\infty}\sum_{i=0}^{L}W\left(\dfrac{t_{i}+t_{i+1}}{2}\right)(W(t_{i+1})-W(t_{i}))\\
& = & \lim_{\delta t\to 0,\,L\to\infty}\sum_{i=0}^{L}\left[\frac{1}{2}(W(t_{i})+W(t_{i+1}))+ Z_{i}\right](W(t_{i+1})-W(t_{i}))\\
& = & \lim_{\delta t\to 0,\,L\to\infty}\sum_{i=0}^{L}\frac{1}{2}\left(W(t_{i+1})^{2}-W(t_{i})^{2}\right)+ \lim_{\delta t\to 0,\,L\to\infty}\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\\
& = & \lim_{\delta t\to 0,\,L\to\infty}\frac{1}{2}\left(W(T)^{2}-W(0)^{2}\right)+ \lim_{\delta t\to 0,\,L\to\infty}\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\\
& = & \frac{1}{2}W(T)^{2}+ \lim_{\delta t\to 0,\,L\to\infty}\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i})).
\end{eqnarray*}
De la igualdad anterior solo nos faltaria demostrar que,
$$
\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\rightarrow 0\text{ en } L^{2}
$$
es decir, 
$$
\lim_{\|\Delta_{L}\|\to0}E\left[\left(\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\right)^{2}\right]=0
$$
Del ejercicio anterior, sabemos que 
$$
 E\left[\left(\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\right)^{2}\right] = O(\delta t)\leq \varepsilon\|\Delta_{L}\|,
$$
así, tomando el limite cuando $\|\Delta_{L}\|\to$ se tiene que,
$$
\sum_{i=0}^{L} Z_{i}(W(t_{i+1})-W(t_{i}))\rightarrow 0\text{ en } L^{2},
$$
por lo tanto, sustituyendo este último resultado, se concluye que
$$
\int_{0}^{T}W(t)dW(t)=\frac{1}{2}W(T)^{2}
$$

:::

::: {#exr-3}
Usando la aproximación de la suma de Riemann
$$
\int_{0}^{T}h(t)dW(t)\sim\sum_{i=0}^{L}h(t_{i})(W(t_{i+1})-W(t_{i})),
$${#eq-aproximacionRiemann}
argumente que,
$$
\mathbb{E}\left[\left(\int_{0}^{T}tdW(t)\right)^{2}\right]=\frac{T^{3}}{3}.
$$
Por tanto, enuncie la isometría de Itô y deduzca que esta isometría es válida para el caso $h(t)=t$.
:::

:::{.proof}
Sea $\{0=t_{0},t_{1},\dots,t_{L-1},t_{L}=T\}$ una partición del intervalo $[0,T]$. De la aproximación de la suma de Riemann, tenemos que
\begin{eqnarray*}
\int_{0}^{T}tdW(t) & \sim & \sum_{i=0}^{L}t_{i}(W(t_{i+1})-W(t_{i}))\\
\Longrightarrow \left(\int_{0}^{T}tdW(t)\right)^{2} & \sim & \left(\sum_{i=0}^{L}t_{i}(W(t_{i+1})-W(t_{i}))\right)^{2},
\end{eqnarray*}
del Teorema Multinomial, se sigue que
$$
\left(\sum_{i=0}^{L}t_{i}(W(t_{i+1})-W(t_{i}))\right)^{2} = \sum_{i=0}^{L}t_{i}^{2}(W(t_{i+1})-W(t_{i}))^{2}+2\sum_{i\neq j}t_{i} t_{j}(W(t_{i+1})-W(t_{i}))(W(t_{j+1})-W(t_{j}))
$$
de las relaciones anteriores se tiene que,
\begin{eqnarray*}
\mathbb{E}
\left[\left(\int_{0}^{T}tdW(t)\right)^{2}\right] & \sim &  \mathbb{E}
\left[\sum_{i=0}^{L}t_{i}^{2}(W(t_{i+1})-W(t_{i}))^{2}+2\sum_{i\neq j}t_{i} t_{j}(W(t_{i+1})-W(t_{i}))(W(t_{j+1})-W(t_{j}))\right]\\
& = &  
\sum_{i=0}^{L}t_{i}^{2}\mathbb{E}(W(t_{i+1})-W(t_{i}))^{2}+2\sum_{i\neq j}t_{i} t_{j}\mathbb{E}\left[(W(t_{i+1})-W(t_{i}))(W(t_{j+1})-W(t_{j}))\right]\\
& = &  
\sum_{i=0}^{L}t_{i}^{2}(t_{i+1}-t_{i}),
\end{eqnarray*}
además, observemos que,
$$
\lim_{L\to 0}\sum_{i=0}^{L}t_{i}^{2}(t_{i+1}-t_{i})=\int_{0}^{T}t^{2}dt=\frac{T}{3}
$$
entonces, de esto último se concluye que,
$$
 \mathbb{E}
\left[\left(\int_{0}^{T}tdW(t)\right)^{2}\right]=\frac{T}{3}.
$$
Por otro lado, de la isometría de Itô, se cumple que
\begin{eqnarray*}
\mathbb{E}
\left[\left(\int_{0}^{T}tdW(t)\right)^{2}\right] & = & \mathbb{E}
\left[\left(\int_{0}^{T}tdW(t)\right)\left(\int_{0}^{T}tdW(t)\right)\right]\\
& = & 
\int_{0}^{T}\mathbb{E}(t^{2})dt\\
& = & 
\int_{0}^{T}t^{2}dt\\
& = & \frac{T}{3}.
\end{eqnarray*}
Por lo tanto, la isometría de Itô se cumple para $h(t)=t$
:::

::: {#exr-4}
Escriba una función de Python para calcular la integral de Itô del movimiento Browniano $W(t)$ sobre $[0,T]$. La función tendría la siguiente firma.
:::