# Tarea 8

::: {#exr-1}

Use la aproximación de la suma de Riemann la ecuación (@eq-aproximacionRiemann). Muestra la propiedad de linealidad de la integral estocástica. Es decir,
$$
\int_{0}^{T}\left(\alpha f(t)+\beta g(t)\right) dW_{t}=\alpha\int_{0}^{T}f(t)dW_{t}+\beta\int_{0}^{T}g(t)dW_{t}
$$

:::

:::{.proof}
Sea $\{0=t_{0},t_{1},\dots,t_{L-1},t_{L}=T\}$ una partición del intervalo $[0,T]$, de la aproximación de la suma de Riemann ecuación (@eq-aproximacionRiemann), se satisface que,
\begin{eqnarray*}
\int_{0}^{T}\left(\alpha f(t)+\beta g(t)\right) dW_{t} & \sim & \sum_{i=0}^{L}(\alpha f(t_{i})+\beta g(t_{i}))(W(t_{i+1})-W(t_{i}))\\
& = & \sum_{i=0}^{L}\alpha f(t_{i})(W(t_{i+1})-W(t_{i}))+ \sum_{i=0}^{L}\beta g(t_{i})(W(t_{i+1})-W(t_{i}))\\
& = & \alpha\sum_{i=0}^{L} f(t_{i})(W(t_{i+1})-W(t_{i}))+\beta\sum_{i=0}^{L} g(t_{i})(W(t_{i+1})-W(t_{i}))
\end{eqnarray*}
observemos que,
$$
\alpha\sum_{i=0}^{L} f(t_{i})(W(t_{i+1})-W(t_{i}))\text{ es la aproximacion de suma de Riemann de; } \alpha\int_{0}^{T} f(t) dW_{t},
$$
análogamente se tiene para $\beta\sum_{i=0}^{L} g(t_{i})(W(t_{i+1})-W(t_{i}))$, por lo tanto de aquí se sigue que, tomando el limite cuando $L\to\infty$, resulta 
$$
\alpha\lim_{L\to\infty}\sum_{i=0}^{L} f(t_{i})(W(t_{i+1})-W(t_{i}))=\alpha \int_{0}^{T}f(t)dW_{t}
$$
y
$$
\beta\lim_{L\to\infty}\sum_{i=0}^{L} g(t_{i})(W(t_{i+1})-W(t_{i}))=\beta\int_{0}^{T}g(t)dW_{t}
$$
entonces de estas dos últimas relaciones, se concluye que:
$$
\int_{0}^{T}\left(\alpha f(t)+\beta g(t)\right) dW_{t}= \alpha \int_{0}^{T}f(t)dW_{t}+\beta\int_{0}^{T}g(t)dW_{t}
$$
:::

::: {#exr-2}
Escriba con detalle la demostración del siguiente Teorema, también incluya la demostración del Lema 5.18 del Mao.
:::
::: {#thm-6.1}

## 6.1 del Mao

Sea $f\in\mathcal{M}^{2}([0,T];\mathbb{R})$, sea $\rho,\tau$ dos tiempos de paro tales que $0\leq\rho\leq\tau\leq T$. Entonces
\begin{eqnarray}
\mathbb{E}\left(\int_{\rho}^{\tau}f(s)dW_{s}\mid\mathcal{F}_{\rho}\right) & = & 0,\\
\mathbb{E}\left(\left|\int_{\rho}^{\tau}f(s)dW_{s}\right|^{2}\mid\mathcal{F}_{\rho}\right) & = & \mathbb{E}\left(\int_{\rho}^{\tau}\left|f(s)\right|^{2}ds\mid\mathcal{F}_{\rho}\right).
\end{eqnarray}
:::
Antes de la demostración del teorema @thm-6.1, veamos el siguiente Lema.\

::: {#lem-5.18}

## 5.18 del Mao
 Sea $f\in\mathcal{M}^{2}([0,T],\mathbb{R})$ y sea $\tau$ un tiempo de paro tal que $0\leq \tau\leq T$. Entonces
$$
\int_{0}^{\tau}f(s)dW(s)=I(\tau),
$$
donde $\{I(t)\}_{0\leq t \leq t}$ es la integral indefinida de $f$ dada por la Definición 5.11.
:::

:::{.proof}

La definición 5.11 del Mao, nos dice que,
$$
I(t)=\int_{0}^{t}f(s)dW(s),\quad 0\leq t\leq T
$$
Por otro lado, de la definición 5.15 del Mao, también se tiene que
$$
\int_{0}^{\tau}f(s)dW(s)=\int_{0}^{T}\mathbb{I}_{[0,\tau]}f(s)dW(s)
$$
así, por las dos definiciones anteriores se cumple que,
$$
\int_{0}^{\tau}f(s)dW(s)=I(\tau)
$$
:::

:::{.proof}
## Del Teorema 6.1
El Teorema de paro de la martingala de Doob, nos dice que:
\begin{equation}
E(I(\tau)|\mathcal{F}_{\rho})=I(\rho)
\end{equation}
Además la definición 5.15, nos dice que
para $\rho$ otro tiempo de paro, tal que $0\leq \rho\leq \tau$, se cumple que
$$
\int_{\rho}^{\tau}f(s)dW(s)=\int_{0}^{\tau}f(s)dW(s)-\int_{0}^{\rho}f(s)dW(s).
$$
Entonces, aplicando la igualdad anterior, el Lema @lem-5.18 y el Teorema de paro de la martingala de Doob, resulta
\begin{eqnarray*}
\mathbb{E}\left(\int_{\rho}^{\tau}f(s)dW_{s}\Big|\mathcal{F}_{\rho}\right) & = & \mathbb{E}\left(\left(\int_{0}^{\tau}f(s)dW(s)-\int_{0}^{\rho}f(s)dW(s)\right)\Big|\mathcal{F}_{\rho}\right)\\
& = & \mathbb{E}(I(\tau)-I(\rho)|\mathcal{F}_\rho)\\
& = & \mathbb{E}(I(\tau)|\mathcal{F}_\rho)-\mathbb{E}(I(\rho)|\mathcal{F}_\rho)\\
& = & I(\rho)-I(\rho)\\
& = & 0
\end{eqnarray*}
De aquí, se concluye que la primera relación del teorema @thm-6.1 se satisface.\
Por otro lado, nuevamente por el Teorema de paro de Doob, se tiene que
\begin{equation}
E(I^{2}(\tau)-\langle I,I\rangle_{\tau}|\mathcal{F}_{\rho})=I^{2}(\rho)-\langle I,I\rangle_{\rho},
\end{equation}
y además, del Teorema 5.14 del Mao, se tiene que
$$
\langle I,I\rangle_{t}=\int_{0}^{t}|f(s)|^{2}ds.
$$
De estos dos hechos anteriores, resulta

\begin{eqnarray*}
\mathbb{E}(|I(\tau)-I(\rho)|^{2}|\mathcal{F}_{\rho}) & = & \mathbb{E}(I^{2}(\tau)-2I(\rho)I(\tau)+I^{2}(\rho)|\mathcal{F}_{\rho}) \\
& = & \mathbb{E}(I^{2}(\tau)|\mathcal{F}_{\rho})-2I(\rho)\mathbb{E}(I(\tau)|\mathcal{F}_{\rho})+I^{2}(\rho) \\
& = & \mathbb{E}(I^{2}(\tau)|\mathcal{F}_{\rho})-2I(\rho)^{2}+I^{2}(\rho)\\
& = & \mathbb{E}(I^{2}(\tau)|\mathcal{F}_{\rho})-I^{2}(\rho)\\
& = & \mathbb{E}(\langle I,I\rangle_{\tau}-\langle I, I\rangle_{\rho}|\mathcal{F}_{\rho})\\
& = & \mathbb{E}\left(\int_{0}^{\tau}|f(s)|^{2}ds-\int_{0}^{\rho}|f(s)|^{2}ds|\mathcal{F}_{\rho}\right)\\
& = & \mathbb{E}\left(\int_{\rho}^{\tau}|f(s)|^{2}ds|\mathcal{F}_{\rho}\right).
\end{eqnarray*}
Ya que, 
$$
\mathbb{E}\left(\left|\int_{\rho}^{\tau}f(s)dW_{s}\right|^{2}\mid\mathcal{F}_{\rho}\right)=\mathbb{E}(|I(\tau)-I(\rho)|^{2}|\mathcal{F}_{\rho}),
$$
se sigue que la segunda relación del teorema @thm-6.1 se satisface.
:::

::: {#exr-3}
Usando la aproximación de la suma de Riemann ecuación (@eq-aproximacionRiemann), la isometría de Itô y la identidad $4ab=(a+b)^{2}-(a-b)^{2}$ pruebe que
$$
\mathbb{E}\left[\left(\int_{0}^{T}g(t)dW_{t}\right)\left(\int_{0}^{T}f(t)dW_{t}\right)\right]=\int_{0}^{T}\mathbb{E}[f(t)g(t)]dt.
$$
:::

:::{.proof}
Sea $a=\int_{0}^{T}g(t)dW_{t}$ y $b=\int_{0}^{T}f(t)dW_{t}$, entonces de la identidad $4ab=(a+b)^{2}-(a-b)^{2}$, se tiene que
\begin{eqnarray*}
4\left(\int_{0}^{T}g(t)dW_{t}\right)\left(\int_{0}^{T}f(t)dW_{t}\right) & = & \left(\int_{0}^{T}g(t)dW_{t}+\int_{0}^{T}f(t)dW_{t}\right)^{2}-\left(\int_{0}^{T}g(t)dW_{t}-\int_{0}^{T}f(t)dW_{t}\right)^{2}\\
& = & \left(\int_{0}^{T}(g(t)+f(t))dW_{t}\right)^{2}-\left(\int_{0}^{T}(g(t)-f(t))dW_{t}\right)^{2},
\end{eqnarray*}
Entonces

\begin{eqnarray*}
4\mathbb{E}\left[\left(\int_{0}^{T}g(t)dW_{t}\right)\left(\int_{0}^{T}f(t)dW_{t}\right)\right] & = & \mathbb{E}\left(\int_{0}^{T}(g(t)+f(t))dW_{t}\right)^{2}-\mathbb{E}\left(\int_{0}^{T}(g(t)-f(t))dW_{t}\right)^{2}\\
& = &\left(\int_{0}^{T} \mathbb{E}(g(t)+f(t))^{2}dt\right)-\left(\int_{0}^{T}\mathbb{E}(g(t)-f(t))^{2}dt\right)\quad\text{esto se sigue por la isometria de Itô}\\
& = & \left(\int_{0}^{T}(\mathbb{E}[(g(t)+f(t))^{2}]-\mathbb{E}[(g(t)-f(t))^{2}])dt\right)\\
& = & \left(\int_{0}^{T}\mathbb{E}[(g(t)+f(t))^{2}-(g(t)-f(t))^{2}]dt\right)\quad\text{usando nuevamente que, } 4ab=(a+b)^{2}-(a-b)^{2}\\
& = & 4\left(\int_{0}^{T}\mathbb{E}[g(t)f(t)]dt\right)
\end{eqnarray*}
De aquí, se concluye que
$$
\mathbb{E}\left[\left(\int_{0}^{T}g(t)dW_{t}\right)\left(\int_{0}^{T}f(t)dW_{t}\right)\right]=\left(\int_{0}^{T}\mathbb{E}[g(t)f(t)]dt\right)
$$
:::

::: {#exr-4}
 Usando la suma de Riemann ecuación (@eq-aproximacionRiemann), deduzca que,
$$
\int_{0}^{T}W(t)^{2}dW(t)=\dfrac{1}{3}W(T)^{3}-\int_{0}^{T}W(t)dt.
$$
:::

:::{.proof}
Sea $\{0=t_{0},t_{1},\dots,t_{L-1},t_{L}=T\}$ una partición del intervalo $[0,T]$.
Primero, observemos que,
$$
3W(t_{i})^{2}(W(t_{i+1})-W(t_{i}))=W(t_{i+1})^{3}-\left(W(t_{i+1})-W(t_{i})\right)^{3}-3\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})-W(t_{i-1})^{3},
$$
entonces de la ecuación (@eq-aproximacionRiemann) y la relación anterior, tenemos que,

\begin{align*}
\int_{0}^{T}W(t)^{2}dW(t) & \sim \sum_{i=0}^{L}W(t_{i})^{2}(W(t_{i+1})-W(t_{i}))\\
& = \frac{1}{3} \sum_{i=0}^{L}\left[W(t_{i+1})^{3}-W(t_{i-1})^{3}\right]-\frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}-\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\\
& =\frac{1}{3}( W(T)^{3}-W(t_{0})^{3})- \frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}-\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\\
& =\frac{1}{3}W(T)^{3}- \frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}-\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i}).
\end{align*}
Afirmamos que $\frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}\to 0$ en $L^{2}$.\
En efecto, calculemos la media de la variación cuadrática. Del Teorema Multinomial, resulta
$$
\frac{1}{9}\mathbb{E}\left[\left(\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}\right)^{2}\right]=\frac{1}{9}\sum_{i=0}^{L}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{6}\right]+\frac{2}{9}\sum_{i\neq j}^{L}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right],
$$
notemos que, como $i\neq j$, sin perdida de generalidad supongamos que $i<j$, entonces

\begin{eqnarray*}
\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right] & = & \mathbb{E}\left.\left\{\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right]\right|\mathcal{F}_{j}\right\}\\
& = & \mathbb{E}\left\{\left(W(t_{i+1})-W(t_{i})\right)^{3}\mathbb{E}\left.\left[\left(W(t_{j+1})-W(t_{j})\right)^{3}\right|\mathcal{F}_{j}\right]\right\}\\
& = & \mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\right]\mathbb{E}\left[\left(W(t_{j+1})-W(t_{j})\right)^{3}\right]
\end{eqnarray*}

dado que de la tarea 5 se demostro que, $\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\right]=0$, de la última igualdad ses concluye que,
$$
\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right]=0.
$$
Por lo tanto,
$$
\frac{2}{9}\sum_{i=0}^{L}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{3}\left(W(t_{j+1})-W(t_{j})\right)^{3}\right]=0.
$$
Por otro lado, también de la tarea 5, sabemos que
$$
\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{6}\right] = 15\left(t_{i+1}-t_{i}\right)^{3},
$$
entonces

\begin{align*}
\frac{1}{9}\sum_{i=0}^{L}E\left[\left(W(t_{i+1})-W(t_{i})\right)^{6}\right] & =\frac{5}{3}\sum_{i=0}^{L}\left(t_{i+1}-t_{i}\right)^{3}\\
& \leq\frac{5}{3}\|\Delta_{L}\|^{2}\sum_{i=0}^{L}\left(t_{i+1}-t_{i}\right)\\
& \leq\frac{5}{3}\|\Delta_{L}\|^{2}L\to0,\quad\text{cuando,  }\|\Delta_{L}\|\to0.
\end{align*}
Con todo lo anterior se concluye que,
$$
\frac{1}{3}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{3}\to 0.
$$
Ahora veamos que,
$$
\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\to \sum_{i=0}^{L}W(t_{i})\left(t_{i+1}-t_{i}\right)\text{ en }L^{2}
$$
Observemos que, 

\begin{eqnarray*}
\mathbb{E}\left[\left(\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})- \sum_{i=0}^{L}W(t_{i})\left(t_{i+1}-t_{i}\right) \right)^{2}\right] & = & \mathbb{E}\left[\left(\sum_{i=0}^{L}W(t_{i})\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right] \right)^{2}\right]\\
& = & \mathbb{E}\left[\sum_{i=0}^{L}W(t_{i})^{2}\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right]^{2} +\sum_{i\neq j}W(t_{i})W(t_{j})\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right]\left[\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)\right] \right]\\
& = & \sum_{i=0}^{L}\mathbb{E}\left[W(t_{i})^{2}\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right]^{2}\right] +\sum_{i\neq j}\mathbb{E}\left[W(t_{i})W(t_{j})\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right]\left[\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)\right] \right],
\end{eqnarray*}
para $i<j$, se tiene que

\begin{eqnarray*}
\mathbb{E}\left[W(t_{i})W(t_{j})\left(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right)\left(\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)\right)\right] & = & \mathbb{E}\left.\left\{\mathbb{E}\left[W(t_{i})W(t_{j})\left(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right)\left(\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)\right)\right]\right|\mathcal{F}_{j}\right\}\\
& = &  \mathbb{E}\left\{W(t_{i})W(t_{j})\left(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right)\mathbb{E}\left[\left.\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)\right|\mathcal{F}_{j}\right]\right\}\\
& = &  \mathbb{E}\left\{W(t_{i})W(t_{j})\left(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right)\mathbb{E}\left[\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)\right]\right\}\\
& = & 0.
\end{eqnarray*}
Por lo tanto,
$$
\sum_{i=0}^{L}W(t_{i})W(t_{j})\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right]\left[\left(W(t_{j+1})-W(t_{j})\right)^{2}-\left(t_{j+1}-t_{j}\right)\right] =0.
$$
Además,
\begin{eqnarray*}
\mathbb{E}\left[W(t_{i})^{2}\left(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right)^{2}\right] & = & \mathbb{E}\left\{\mathbb{E}\left.\left[W(t_{i})^{2}\left(\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right)^{2}\right]\right|\mathcal{F}_{i}\right\}\\
& = & \mathbb{E}\left.\left\{\mathbb{E}\left[W(t_{i})^{2}\left(\left(W(t_{i+1})-W(t_{i})\right)^{4}-2\left(W(t_{i+1})-W(t_{i})\right)^{2}\left(t_{i+1}-t_{i}\right)+\left(t_{i+1}-t_{i}\right)^{2}\right)\right]\right|\mathcal{F}_{i}\right\}\\
& = & \mathbb{E}\left\{\mathbb{E}\left.\left[W(t_{i})^{2}\left(W(t_{i+1})-W(t_{i})\right)^{4}-2W(t_{i})^{2}\left(W(t_{i+1})-W(t_{i})\right)^{2}\left(t_{i+1}-t_{i}\right)+W(t_{i})^{2}\left(t_{i+1}-t_{i}\right)^{2}\right]\right|\mathcal{F}_{i}\right\}\\
& = & \mathbb{E}\left\{\mathbb{E}\left[\left.W(t_{i})^{2}\left(W(t_{i+1})-W(t_{i})\right)^{4}\right|\mathcal{F}_{i}\right]-2\mathbb{E}\left[\left.W(t_{i})^{2}\left(W(t_{i+1})-W(t_{i})\right)^{2}\left(t_{i+1}-t_{i}\right)\right|\mathcal{F}_{i}\right]+\mathbb{E}\left[\left.W(t_{i})^{2}\left(t_{i+1}-t_{i}\right)^{2}\right|\mathcal{F}_{i}\right]\right\}\\
& = & \mathbb{E}\left\{W(t_{i})^{2}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{4}|\mathcal{F}_{i}\right]-2W(t_{i})^{2}\mathbb{E}\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}\left(t_{i+1}-t_{i}\right)|\mathcal{F}_{i}\right]+W(t_{i})^{2}\mathbb{E}\left[\left(t_{i+1}-t_{i}\right)^{2}|\mathcal{F}_{i}\right]\right\}\\
& = & \mathbb{E}\left\{W(t_{i})^{2}3(t_{i+1}-t_{i})^{2}-2W(t_{i})^{2}(t_{i+1}-t_{i})^{2}+W(t_{i})^{2}\left(t_{i+1}-t_{i}\right)^{2}\right\}\\
& = & 3t_{i}(t_{i+1}-t_{i})^{2}-2t_{i}(t_{i+1}-t_{i})^{2}+t_{i}(t_{i+1}-t_{i})^{2}\\
& = & 2t_{i}(t_{i+1}-t_{i})^{2},
\end{eqnarray*}
de esta última igualdad se sigue que,

\begin{eqnarray*}
\mathbb{E}\left[\sum_{i=0}^{L}W(t_{i})^{2}\left[\left(W(t_{i+1})-W(t_{i})\right)^{2}-\left(t_{i+1}-t_{i}\right)\right]^{2}\right] & = & \sum_{i=0}^{L}2t_{i}(t_{i+1}-t_{i})^{2}\\
& \leq & 2L\|\Delta_{L}\|\sum_{i=0}^{L}t_{i+1}-t_{i}\\
& = & 2\|\Delta_{L}\|L^{2}\to0,\quad\text{ cuando }\|\Delta_{L}\|\to0.
\end{eqnarray*}
Por lo tanto,
$$
\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\to \sum_{i=0}^{L}W(t_{i})\left(t_{i+1}-t_{i}\right).
$$
Así, sustituyendo todo lo anterior, resulta

\begin{eqnarray*}
\int_{0}^{T}W(t)^{2}dW(t) & = & \lim_{L\to\infty}\frac{1}{3}W(T)^{3}-\lim_{L\to\infty}\sum_{i=0}^{L}\left(W(t_{i+1})-W(t_{i})\right)^{2}W(t_{i})\\
& = & \frac{1}{3}W(T)^{3}-\int_{0}^{T}W(t)dt
\end{eqnarray*}

:::

::: {#exr-5}
Verifique que la isometría de Itô, dada por
$$
\mathbb{E}\left[\left(\int_{0}^{T}h(t)dW(t)\right)^{2}\right]=\mathbb{E}\left[\int_{0}^{T}h(t)^{2}dt\right],
$$
se tiene cuando $h(t):= 1$.
:::

:::{.proof}
Del ejercicio @exr-3 con $h(t)=1$, se tiene que,

\begin{eqnarray*}
\mathbb{E}\left[\left(\int_{0}^{T}h(t)dW(t)\right)^{2}\right]=\mathbb{E}\left[\left(\int_{0}^{T}1dW(t)\right)^{2}\right] & = & \mathbb{E}\left[\left(\int_{0}^{T}1dW_{t}\right)\left(\int_{0}^{T}1dW_{t}\right)\right]\\
& = & \int_{0}^{T}\mathbb{E}[1]dt\\
& = & \int_{0}^{T}dt\\
& = & T.
\end{eqnarray*}
Por otro lado,
\begin{eqnarray*}
\mathbb{E}\left[\int_{0}^{T}h(t)^{2}dt\right] & = & \mathbb{E}\left[\int_{0}^{T}1^{2}dt\right]\\
& = & \mathbb{E}\left[\int_{0}^{T}dt\right]\\
& = & \mathbb{E}\left[T\right]\\
& = & T
\end{eqnarray*}
Así,
$$
\mathbb{E}\left[\left(\int_{0}^{T}dW(t)\right)^{2}\right]= \mathbb{E}\left[\int_{0}^{T}dt\right],
$$
y con esto se concluye que, para $h(t)=1$ se satisface que
$$
\mathbb{E}\left[\left(\int_{0}^{T}h(t)dW(t)\right)^{2}\right]= \mathbb{E}\left[\int_{0}^{T}h(t)^{2}dt\right].
$$
:::